### ISSUE TITLE
Add Filter by file type

### ISSUE THREAD

**Issue by davidchalifoux** [putdotio/putio.js#6]
The API documentation notes that `file_type` is an available filter on the /files/list endpoint, but it is not implemented at https://github.com/putdotio/putio.js/blob/master/src/resources/Files/Files.ts

**Comment by altayaydemir** [comment]
👍 👍 👍

**Comment by altayaydemir** [comment]
added in [v8.6.0](https://github.com/putdotio/putio.js/releases/tag/v8.6.0)
